name: model-training

on:
  pull_request:
    branches:
      - master

env: 
  repo_token: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  train-current:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - uses: actions/checkout@v2.3.2
      - name: prepare current version report
        run: |
          pip install -r requirements.txt
          dvc repro train_model

          dvc exp run train_model --queue --set-param param=2
          dvc exp run train_model --queue --set-param param=3

          dvc exp run --run-all

